[package]
name = "msgpack_rmp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmp = "0.8"
rmp-serde = "1"
serde = "1"
serde_derive = "1"

[[bin]]
name = "rmp"
path = "src/main.rs"
