[package]
name = "globset-example"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]
edition = "2018"

[dependencies]
globset = "0.3"

[[bin]]
name = "simple"
path = "src/main.rs"

[[bin]]
name = "custom"
path = "src/custom.rs"

[[bin]]
name = "many"
path = "src/many.rs"
