[package]
name = "rpc"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[dependencies]
msgpack-rpc = { git = "https://github.com/hhatto/msgpack-rpc-rust.git", branch = "master" }
rmp = "0.7"

[[bin]]
name = "msgpack-rpc"
path = "src/msgpack-rpc-echo.rs"
