[package]
name = "fast-woothee"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[lib]
name = "woothee"
crate-type = ["cdylib"]

[dependencies]
woothee = "0.13"

[dependencies.cpython]
version = "0.7"
features = ["extension-module"]
