[package]
name = "http-client"
version = "0.1.0"
authors = ["hhatto <hhatto.jp@gmail.com>"]

[dependencies]
hyper = "*"
rustc-serialize = "0.3"

[[bin]]
name = "get-json-hyper"
path = "src/get-json-hyper.rs"
