[package]
name = "mio"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[dependencies]
mio = "0.5"

[dependencies.bytes]
git = "https://github.com/carllerche/bytes"

[[bin]]
name = "uds-client"
path = "src/uds-client.rs"
