[package]
name = "diesel_mysql"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[dependencies]
diesel = { version = "0.11", features = ["mysql"] }
diesel_codegen  = { version = "0.11", features = ["mysql"] }
dotenv = "0.8"
