[package]
name = "pyo3-woothee"
version = "0.1.0"
authors = ["Hideo Hattori <hhatto.jp@gmail.com>"]

[lib]
name = "woothee"
crate-type = ["cdylib"]

[dependencies]
woothee = "0.8"

[dependencies.pyo3]
version = "0.16"
features = ["extension-module"]
